# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.
[libraries]
proj.files = [
  'rv32.vhd',
  'rv32_tb.vhd',
]
test.files = [
  'main.vhd',
  'isim.vhd',
]